import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog
from processData import *
import logging


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        QtCore.QObject.__init__(self)
        config = ConfigParser()
        config.read('config.ini')
        okay = -1
        txt = ""
        while okay == -1:
            if config['DEFAULT']['STATION']:
                if not txt:
                    self.show_stationPopup(
                        "Enter your callsign (e.g. EDDM_TWR) or press Enter to choose the last controlled station.")
                else:
                    self.show_stationPopup("Enter another station.")
                if self.station == "":
                    self.station = config['DEFAULT']['STATION']
                    logging.debug("Last station")
            else:
                self.show_stationPopup("Enter your callsign (e.g. EDDM_TWR).")
            txt, okay = check_station(self.station)
            if txt != "Station online":
                self.show_errorPopup(txt)
        self.update_config(config, 'STATION', self.station)

        logging.info(f"Station: {self.station}")
        self.choose_chart()
        self.timeTimer = QtCore.QTimer()
        self.timeTimer.timeout.connect(self.updateTime)
        self.timeTimer.start(250)
        self.updateTimer = QtCore.QTimer()
        self.updateTimer.timeout.connect(self.updateUi)
        self.updateTimer.start(60000)
        logging.info("Timer set")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GVMC = QtWidgets.QGroupBox(self.centralwidget)
        self.GVMC.setGeometry(QtCore.QRect(680, 170, 81, 51))
        self.GVMC.setTitle("")
        self.GVMC.setObjectName("GVMC")
        self.currCond = QtWidgets.QLabel(self.GVMC)
        self.currCond.setGeometry(QtCore.QRect(0, 0, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.currCond.setFont(font)
        self.currCond.setAlignment(QtCore.Qt.AlignCenter)
        self.currCond.setObjectName("currCond")
        self.GQNHDescriptor = QtWidgets.QGroupBox(self.centralwidget)
        self.GQNHDescriptor.setGeometry(QtCore.QRect(10, 950, 91, 41))
        self.GQNHDescriptor.setTitle("")
        self.GQNHDescriptor.setObjectName("GQNHDescriptor")
        self.QNHDescriptor = QtWidgets.QLabel(self.GQNHDescriptor)
        self.QNHDescriptor.setGeometry(QtCore.QRect(0, 0, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.QNHDescriptor.setFont(font)
        self.QNHDescriptor.setAlignment(QtCore.Qt.AlignCenter)
        self.QNHDescriptor.setObjectName("QNHDescriptor")
        self.GcurrInch = QtWidgets.QGroupBox(self.centralwidget)
        self.GcurrInch.setGeometry(QtCore.QRect(309, 949, 81, 41))
        self.GcurrInch.setTitle("")
        self.GcurrInch.setObjectName("GcurrInch")
        self.currInch = QtWidgets.QLabel(self.GcurrInch)
        self.currInch.setGeometry(QtCore.QRect(0, 2, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.currInch.setFont(font)
        self.currInch.setAlignment(QtCore.Qt.AlignCenter)
        self.currInch.setObjectName("currInch")
        self.GClock = QtWidgets.QGroupBox(self.centralwidget)
        self.GClock.setGeometry(QtCore.QRect(1720, 930, 191, 61))
        self.GClock.setTitle("")
        self.GClock.setObjectName("GClock")
        self.currTime = QtWidgets.QLabel(self.GClock)
        self.currTime.setGeometry(QtCore.QRect(-20, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.currTime.setFont(font)
        self.currTime.setAutoFillBackground(False)
        self.currTime.setInputMethodHints(QtCore.Qt.ImhTime)
        self.currTime.setAlignment(QtCore.Qt.AlignCenter)
        self.currTime.setObjectName("currTime")
        self.currMin = QtWidgets.QLabel(self.GClock)
        self.currMin.setGeometry(QtCore.QRect(70, 0, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(32)
        self.currMin.setFont(font)
        self.currMin.setAlignment(QtCore.Qt.AlignCenter)
        self.currMin.setObjectName("currMin")
        self.GAtisLetter = QtWidgets.QGroupBox(self.centralwidget)
        self.GAtisLetter.setGeometry(QtCore.QRect(1060, 110, 141, 111))
        self.GAtisLetter.setTitle("")
        self.GAtisLetter.setObjectName("GAtisLetter")
        self.currAtisLetter = QtWidgets.QLabel(self.GAtisLetter)
        self.currAtisLetter.setGeometry(QtCore.QRect(10, 10, 121, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        self.currAtisLetter.setFont(font)
        self.currAtisLetter.setAlignment(QtCore.Qt.AlignCenter)
        self.currAtisLetter.setObjectName("currAtisLetter")
        self.GWinfInfo2 = QtWidgets.QGroupBox(self.centralwidget)
        self.GWinfInfo2.setGeometry(QtCore.QRect(1280, 50, 631, 211))
        self.GWinfInfo2.setTitle("")
        self.GWinfInfo2.setObjectName("GWinfInfo2")
        self.currWindDir2 = QtWidgets.QLabel(self.GWinfInfo2)
        self.currWindDir2.setGeometry(QtCore.QRect(6, 2, 341, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        self.currWindDir2.setFont(font)
        self.currWindDir2.setAlignment(QtCore.Qt.AlignCenter)
        self.currWindDir2.setObjectName("currWindDir2")
        self.highWindDir2 = QtWidgets.QLabel(self.GWinfInfo2)
        self.highWindDir2.setGeometry(QtCore.QRect(280, 10, 101, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.highWindDir2.setFont(font)
        self.highWindDir2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.highWindDir2.setObjectName("highWindDir2")
        self.lowWindDir2 = QtWidgets.QLabel(self.GWinfInfo2)
        self.lowWindDir2.setGeometry(QtCore.QRect(-30, 10, 111, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.lowWindDir2.setFont(font)
        self.lowWindDir2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lowWindDir2.setObjectName("lowWindDir2")
        self.currWindSpd2 = QtWidgets.QLabel(self.GWinfInfo2)
        self.currWindSpd2.setGeometry(QtCore.QRect(360, 0, 271, 231))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        self.currWindSpd2.setFont(font)
        self.currWindSpd2.setAlignment(QtCore.Qt.AlignCenter)
        self.currWindSpd2.setObjectName("currWindSpd2")
        self.highWindSpd2 = QtWidgets.QLabel(self.GWinfInfo2)
        self.highWindSpd2.setGeometry(QtCore.QRect(570, 10, 61, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.highWindSpd2.setFont(font)
        self.highWindSpd2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.highWindSpd2.setObjectName("highWindSpd2")
        self.lowWindSpd2 = QtWidgets.QLabel(self.GWinfInfo2)
        self.lowWindSpd2.setGeometry(QtCore.QRect(380, 10, 51, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.lowWindSpd2.setFont(font)
        self.lowWindSpd2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lowWindSpd2.setObjectName("lowWindSpd2")
        self.arrowR2 = QtWidgets.QLabel(self.GWinfInfo2)
        self.arrowR2.setGeometry(QtCore.QRect(230, 110, 21, 21))
        self.arrowR2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arrowR2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.arrowR2.setText("")
        self.arrowR2.setPixmap(QtGui.QPixmap("pictures/arrow_r.jpg"))
        self.arrowR2.setScaledContents(True)
        self.arrowR2.setWordWrap(False)
        self.arrowR2.setObjectName("arrowR2")
        self.arrowL2 = QtWidgets.QLabel(self.GWinfInfo2)
        self.arrowL2.setGeometry(QtCore.QRect(100, 110, 21, 21))
        self.arrowL2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arrowL2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.arrowL2.setText("")
        self.arrowL2.setPixmap(QtGui.QPixmap("pictures/arrow_l.jpg"))
        self.arrowL2.setScaledContents(True)
        self.arrowL2.setWordWrap(False)
        self.arrowL2.setObjectName("arrowL2")
        self.arrowD2 = QtWidgets.QLabel(self.GWinfInfo2)
        self.arrowD2.setGeometry(QtCore.QRect(440, 110, 21, 21))
        self.arrowD2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arrowD2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.arrowD2.setText("")
        self.arrowD2.setPixmap(QtGui.QPixmap("pictures/arrow_d.jpg"))
        self.arrowD2.setScaledContents(True)
        self.arrowD2.setWordWrap(False)
        self.arrowD2.setObjectName("arrowD2")
        self.arrowU2 = QtWidgets.QLabel(self.GWinfInfo2)
        self.arrowU2.setGeometry(QtCore.QRect(530, 110, 21, 21))
        self.arrowU2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arrowU2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.arrowU2.setText("")
        self.arrowU2.setPixmap(QtGui.QPixmap("pictures/arrow_u.jpg"))
        self.arrowU2.setScaledContents(True)
        self.arrowU2.setWordWrap(False)
        self.arrowU2.setObjectName("arrowU2")
        self.GWindInfo1 = QtWidgets.QGroupBox(self.centralwidget)
        self.GWindInfo1.setGeometry(QtCore.QRect(10, 50, 631, 211))
        self.GWindInfo1.setTitle("")
        self.GWindInfo1.setObjectName("GWindInfo1")
        self.currWindDir = QtWidgets.QLabel(self.GWindInfo1)
        self.currWindDir.setGeometry(QtCore.QRect(6, 2, 341, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        self.currWindDir.setFont(font)
        self.currWindDir.setAlignment(QtCore.Qt.AlignCenter)
        self.currWindDir.setObjectName("currWindDir")
        self.highWindDir = QtWidgets.QLabel(self.GWindInfo1)
        self.highWindDir.setGeometry(QtCore.QRect(270, 10, 111, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.highWindDir.setFont(font)
        self.highWindDir.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.highWindDir.setObjectName("highWindDir")
        self.lowWindDir = QtWidgets.QLabel(self.GWindInfo1)
        self.lowWindDir.setGeometry(QtCore.QRect(-30, 10, 111, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.lowWindDir.setFont(font)
        self.lowWindDir.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lowWindDir.setObjectName("lowWindDir")
        self.currWindSpd = QtWidgets.QLabel(self.GWindInfo1)
        self.currWindSpd.setGeometry(QtCore.QRect(360, 0, 271, 231))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(40)
        self.currWindSpd.setFont(font)
        self.currWindSpd.setAlignment(QtCore.Qt.AlignCenter)
        self.currWindSpd.setObjectName("currWindSpd")
        self.highWindSpd = QtWidgets.QLabel(self.GWindInfo1)
        self.highWindSpd.setGeometry(QtCore.QRect(560, 10, 71, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.highWindSpd.setFont(font)
        self.highWindSpd.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.highWindSpd.setObjectName("highWindSpd")
        self.lowWindSpd = QtWidgets.QLabel(self.GWindInfo1)
        self.lowWindSpd.setGeometry(QtCore.QRect(380, 10, 51, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.lowWindSpd.setFont(font)
        self.lowWindSpd.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lowWindSpd.setObjectName("lowWindSpd")
        self.arrowR = QtWidgets.QLabel(self.GWindInfo1)
        self.arrowR.setGeometry(QtCore.QRect(230, 110, 21, 21))
        self.arrowR.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arrowR.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.arrowR.setText("")
        self.arrowR.setPixmap(QtGui.QPixmap("pictures/arrow_r.jpg"))
        self.arrowR.setScaledContents(True)
        self.arrowR.setWordWrap(False)
        self.arrowR.setObjectName("arrowR")
        self.arrowL = QtWidgets.QLabel(self.GWindInfo1)
        self.arrowL.setGeometry(QtCore.QRect(100, 110, 21, 21))
        self.arrowL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arrowL.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.arrowL.setText("")
        self.arrowL.setPixmap(QtGui.QPixmap("pictures/arrow_l.jpg"))
        self.arrowL.setScaledContents(True)
        self.arrowL.setWordWrap(False)
        self.arrowL.setObjectName("arrowL")
        self.arrowD = QtWidgets.QLabel(self.GWindInfo1)
        self.arrowD.setGeometry(QtCore.QRect(440, 110, 21, 21))
        self.arrowD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arrowD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.arrowD.setText("")
        self.arrowD.setPixmap(QtGui.QPixmap("pictures/arrow_d.jpg"))
        self.arrowD.setScaledContents(True)
        self.arrowD.setWordWrap(False)
        self.arrowD.setObjectName("arrowD")
        self.arrowU = QtWidgets.QLabel(self.GWindInfo1)
        self.arrowU.setGeometry(QtCore.QRect(530, 110, 21, 21))
        self.arrowU.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arrowU.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.arrowU.setText("")
        self.arrowU.setPixmap(QtGui.QPixmap("pictures/arrow_u.jpg"))
        self.arrowU.setScaledContents(True)
        self.arrowU.setWordWrap(False)
        self.arrowU.setObjectName("arrowU")
        self.GBR1 = QtWidgets.QGroupBox(self.centralwidget)
        self.GBR1.setGeometry(QtCore.QRect(10, 10, 631, 41))
        self.GBR1.setTitle("")
        self.GBR1.setObjectName("GBR1")
        self.br1 = QtWidgets.QLabel(self.GBR1)
        self.br1.setGeometry(QtCore.QRect(0, 10, 631, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.br1.setFont(font)
        self.br1.setAlignment(QtCore.Qt.AlignCenter)
        self.br1.setObjectName("br1")
        self.GcurrQNH = QtWidgets.QGroupBox(self.centralwidget)
        self.GcurrQNH.setGeometry(QtCore.QRect(110, 930, 191, 61))
        self.GcurrQNH.setTitle("")
        self.GcurrQNH.setObjectName("GcurrQNH")
        self.currQNH = QtWidgets.QLabel(self.GcurrQNH)
        self.currQNH.setGeometry(QtCore.QRect(-20, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.currQNH.setFont(font)
        self.currQNH.setAutoFillBackground(False)
        self.currQNH.setAlignment(QtCore.Qt.AlignCenter)
        self.currQNH.setObjectName("currQNH")
        self.GBR2 = QtWidgets.QGroupBox(self.centralwidget)
        self.GBR2.setGeometry(QtCore.QRect(1280, 10, 631, 41))
        self.GBR2.setTitle("")
        self.GBR2.setObjectName("GBR2")
        self.br2 = QtWidgets.QLabel(self.GBR2)
        self.br2.setGeometry(QtCore.QRect(0, 10, 631, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.br2.setFont(font)
        self.br2.setAlignment(QtCore.Qt.AlignCenter)
        self.br2.setObjectName("br2")
        self.GAddInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.GAddInfo.setGeometry(QtCore.QRect(1240, 900, 471, 91))
        self.GAddInfo.setTitle("")
        self.GAddInfo.setObjectName("GAddInfo")
        self.cloudInfo = QtWidgets.QLabel(self.GAddInfo)
        self.cloudInfo.setGeometry(QtCore.QRect(120, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.cloudInfo.setFont(font)
        self.cloudInfo.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.cloudInfo.setObjectName("cloudInfo")
        self.visibility = QtWidgets.QLabel(self.GAddInfo)
        self.visibility.setGeometry(QtCore.QRect(10, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.visibility.setFont(font)
        self.visibility.setObjectName("visibility")
        self.currTemp = QtWidgets.QLabel(self.GAddInfo)
        self.currTemp.setGeometry(QtCore.QRect(10, 60, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.currTemp.setFont(font)
        self.currTemp.setObjectName("currTemp")
        self.currDewPoint = QtWidgets.QLabel(self.GAddInfo)
        self.currDewPoint.setGeometry(QtCore.QRect(120, 60, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.currDewPoint.setFont(font)
        self.currDewPoint.setObjectName("currDewPoint")
        self.GAirport = QtWidgets.QGroupBox(self.centralwidget)
        self.GAirport.setGeometry(QtCore.QRect(680, 110, 81, 51))
        self.GAirport.setTitle("")
        self.GAirport.setObjectName("GAirport")
        self.airport = QtWidgets.QLabel(self.GAirport)
        self.airport.setGeometry(QtCore.QRect(0, 0, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.airport.setFont(font)
        self.airport.setAlignment(QtCore.Qt.AlignCenter)
        self.airport.setObjectName("airport")
        self.chart = QtWidgets.QLabel(self.centralwidget)
        self.chart.setGeometry(QtCore.QRect(0, 270, 1920, 620))
        self.chart.setText("")
        self.chart.setPixmap(QtGui.QPixmap(self.chartfile))
        self.chart.setScaledContents(True)
        self.chart.setAlignment(QtCore.Qt.AlignCenter)
        self.chart.setWordWrap(False)
        self.chart.setObjectName("chart")
        MainWindow.setCentralWidget(self.centralwidget)
        self.currGust = QtWidgets.QLabel(self.GWindInfo1)
        self.currGust.setGeometry(QtCore.QRect(0, 170, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        self.currGust.setFont(font)
        self.currGust.setAlignment(QtCore.Qt.AlignCenter)
        self.currGust.setObjectName("currGust")
        self.currGust2 = QtWidgets.QLabel(self.GWinfInfo2)
        self.currGust2.setGeometry(QtCore.QRect(0, 170, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        self.currGust2.setFont(font)
        self.currGust2.setAlignment(QtCore.Qt.AlignCenter)
        self.currGust2.setObjectName("currGust2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        logging.info("UI setup completed")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"IDVS - {self.station}"))
        MainWindow.setWindowIcon(QtGui.QIcon('pictures/logo.jpeg'))
        self.airport.setText(_translate("MainWindow", self.station[:4]))
        self.QNHDescriptor.setText("QNH")
        logging.info("UI retranslated")

    def updateUi(self):
        atis = Atis(self.station)
        metar = Metar()
        metar.get_metar(atis.get_metar())
        rwy1, rwy2 = atis.get_runways()
        self.br1.setText(rwy1)
        self.br2.setText(rwy2)
        self.cloudInfo.setText(metar.get_clouds())
        self.currAtisLetter.setText(atis.get_atisLetter())
        self.currCond.setText(metar.is_vmc())
        self.currDewPoint.setText(metar.get_dewpoint())
        self.currInch.setText(metar.get_inch())
        self.currQNH.setText(metar.get_qnh())
        self.currTemp.setText(metar.get_temp())
        self.currWindDir.setText(metar.get_winddir())
        self.currWindDir2.setText(metar.get_winddir())
        self.currWindSpd.setText(metar.get_windspd())
        self.currWindSpd2.setText(metar.get_windspd())
        highWinddir = metar.get_winddir("max")
        self.highWindDir.setText(highWinddir)
        self.highWindDir2.setText(highWinddir)
        lowWindDir = metar.get_winddir("min")
        self.lowWindDir.setText(lowWindDir)
        self.lowWindDir2.setText(lowWindDir)
        highWindSpd = metar.get_windspd("max")
        self.highWindSpd.setText(highWindSpd)
        self.highWindSpd2.setText(highWindSpd)
        lowWindSpd = metar.get_windspd("min")
        self.lowWindSpd.setText(lowWindSpd)
        self.lowWindSpd2.setText(lowWindSpd)
        self.visibility.setText(metar.get_visibility())
        self.currGust.setText(f"Gusting: {metar.get_gust()}" if metar.get_gust() != None else "")
        self.currGust2.setText(f"Gusting: {metar.get_gust()}" if metar.get_gust() != None else "")
        logging.info("UI updated")

    def updateTime(self):
        self.currTime.setText(f"{get_utc_hour()}:       :{get_utc_second()}")
        self.currMin.setText(f"{get_utc_minute()}")
        logging.debug("Time updated")

    def show_stationPopup(self, msg):
        self.station, done1 = QtWidgets.QInputDialog.getText(self, "Enter controlled position", msg,
                                                             flags=QtCore.Qt.Popup)
        self.station = self.station.upper()
        if done1:
            return
        else:
            logging.critical("Closed station input")
            sys.exit(1)

    def show_errorPopup(self, msg):
        button = QMessageBox.critical(self, "Error", msg, QMessageBox.Retry | QMessageBox.Close, QMessageBox.Retry)
        if button == QMessageBox.Close:
            logging.critical("Closed error box after station input")
            sys.exit(1)

    def choose_chart(self):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Choose a chart to be displayed")
        msg.setInformativeText("Size should be 1920*620")
        msg.setWindowTitle("Choose chart")
        msg.addButton(QMessageBox.Open)
        msg.addButton(QMessageBox.Close)
        msg.setDefaultButton(QMessageBox.Open)
        msg.setEscapeButton(QMessageBox.Close)
        msg.exec_()
        if msg.clickedButton() == msg.button(QMessageBox.Close):
            logging.critical("Closed chart messagebox")
            sys.exit(1)
        fileName, check = QFileDialog.getOpenFileName(self, "Choose chart to display", "",
                                                      "All Files (*);;JPEG Files (*.jpg, *.jpeg);;PNG Files (*.png)")
        if check:
            logging.info("File chosen")
            self.chartfile = fileName
        else:
            logging.critical("Exited during file browser")
            sys.exit(1)

    def update_config(self, configHandler: ConfigParser, option, value):
        configHandler.set('DEFAULT', option, value)
        with open('config.ini', 'w+') as cfg:
            configHandler.write(cfg)


def set_Logger():
    log = logging.basicConfig(filename="log.log", filemode="w",
                              format="%(asctime)s\t%(levelname)s\t%(filename)s:%(lineno)s\t\t%(message)s",
                              datefmt="%H:%M:%S")
    log = logging.getLogger()
    config = ConfigParser()
    config.read('config.ini')
    if config['DEFAULT']['LOGGER'].upper() == "DEBUG":
        log.setLevel(logging.DEBUG)
    elif config['DEFAULT']['LOGGER'].upper() == "INFO":
        log.setLevel(logging.INFO)
    elif config['DEFAULT']['LOGGER'].upper() == "WARNING":
        log.setLevel(logging.WARNING)
    elif config['DEFAULT']['LOGGER'].upper() == "ERROR":
        log.setLevel(logging.ERROR)
    elif config['DEFAULT']['LOGGER'].upper() == "CRITICAL":
        log.setLevel(logging.CRITICAL)
    logging.info("Logger set")


if __name__ == "__main__":
    set_Logger()
    logging.info("Starting")
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.updateTime()
    ui.updateUi()
    MainWindow.showMaximized()
    logging.info("Window shown")
    sys.exit(app.exec_())
